"""reservas multi-mesa: tabla reserva_mesas, duracion_minutos

Revision ID: 0950e2556799
Revises: a385fda63026
Create Date: 2026-08-04 07:04:09.379087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0950e2556799'
down_revision: Union[str, None] = 'a385fda63026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva_mesas',
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('mesa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserva_id', 'mesa_id')
    )
    op.add_column('reservas', sa.Column('duracion_minutos', sa.Integer(), server_default='90', nullable=False))
    op.drop_index('ix_reservas_mesa_id', table_name='reservas')
    op.drop_constraint('reservas_mesa_id_fkey', 'reservas', type_='foreignkey')
    op.drop_column('reservas', 'mesa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('mesa_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('reservas_mesa_id_fkey', 'reservas', 'mesas', ['mesa_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_reservas_mesa_id', 'reservas', ['mesa_id'], unique=False)
    op.drop_column('reservas', 'duracion_minutos')
    op.drop_table('reserva_mesas')
    # ### end Alembic commands ###
