"""conexion google calendar por restaurante

Revision ID: 1247fead47d3
Revises: 82670fb20f91
Create Date: 2026-08-05 09:47:07.057498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1247fead47d3'
down_revision: Union[str, None] = '82670fb20f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_conexiones',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('access_token_cifrado', sa.Text(), nullable=False),
    sa.Column('refresh_token_cifrado', sa.Text(), nullable=False),
    sa.Column('token_expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), server_default='primary', nullable=False),
    sa.Column('email_cuenta', sa.String(length=255), nullable=True),
    sa.Column('canal_id', sa.String(length=255), nullable=True),
    sa.Column('canal_resource_id', sa.String(length=255), nullable=True),
    sa.Column('canal_expira_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_calendar_conexiones_restaurante_id'), 'google_calendar_conexiones', ['restaurante_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_calendar_conexiones_restaurante_id'), table_name='google_calendar_conexiones')
    op.drop_table('google_calendar_conexiones')
    # ### end Alembic commands ###
