"""dias especiales cierres

Revision ID: 29db4e2ab955
Revises: 40369b4afebc
Create Date: 2026-08-06 08:21:12.323630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29db4e2ab955'
down_revision: Union[str, None] = '40369b4afebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias_especiales',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cerrado', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurante_id', 'fecha', name='uq_dia_especial_restaurante_fecha')
    )
    op.create_index(op.f('ix_dias_especiales_fecha'), 'dias_especiales', ['fecha'], unique=False)
    op.create_index(op.f('ix_dias_especiales_restaurante_id'), 'dias_especiales', ['restaurante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dias_especiales_restaurante_id'), table_name='dias_especiales')
    op.drop_index(op.f('ix_dias_especiales_fecha'), table_name='dias_especiales')
    op.drop_table('dias_especiales')
    # ### end Alembic commands ###
