"""precio medio por persona para estadisticas

Revision ID: 40369b4afebc
Revises: 5f6492831464
Create Date: 2026-08-06 08:14:11.349164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40369b4afebc'
down_revision: Union[str, None] = '5f6492831464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurantes', sa.Column('precio_medio_por_persona', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurantes', 'precio_medio_por_persona')
    # ### end Alembic commands ###
