"""encuesta de satisfaccion post visita

Revision ID: 5f6492831464
Revises: 73e18d369141
Create Date: 2026-08-06 07:52:37.554518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6492831464'
down_revision: Union[str, None] = '73e18d369141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('encuesta_enviada_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reservas', sa.Column('encuesta_puntuacion', sa.Integer(), nullable=True))
    op.add_column('reservas', sa.Column('encuesta_comentario', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'encuesta_comentario')
    op.drop_column('reservas', 'encuesta_puntuacion')
    op.drop_column('reservas', 'encuesta_enviada_en')
    # ### end Alembic commands ###
