"""modelo cliente y vinculo con reserva

Revision ID: 73e18d369141
Revises: b559e74266a0
Create Date: 2026-08-06 07:43:24.753537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e18d369141'
down_revision: Union[str, None] = 'b559e74266a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('vip', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('alergenos_notas', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurante_id', 'telefono', name='uq_cliente_restaurante_telefono')
    )
    op.create_index(op.f('ix_clientes_restaurante_id'), 'clientes', ['restaurante_id'], unique=False)
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=False)
    op.add_column('reservas', sa.Column('cliente_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reservas_cliente_id'), 'reservas', ['cliente_id'], unique=False)
    op.create_foreign_key(None, 'reservas', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.drop_index(op.f('ix_reservas_cliente_id'), table_name='reservas')
    op.drop_column('reservas', 'cliente_id')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_restaurante_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
