"""recordatorio automatico de reserva

Revision ID: 80e5f6e55868
Revises: 1247fead47d3
Create Date: 2026-08-06 06:31:16.569289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e5f6e55868'
down_revision: Union[str, None] = '1247fead47d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('recordatorio_enviado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('restaurantes', sa.Column('recordatorio_horas_antes', sa.Integer(), server_default='3', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurantes', 'recordatorio_horas_antes')
    op.drop_column('reservas', 'recordatorio_enviado_en')
    # ### end Alembic commands ###
