"""api key de integracion por restaurante

Revision ID: 82670fb20f91
Revises: 0950e2556799
Create Date: 2026-08-05 07:54:38.911428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82670fb20f91'
down_revision: Union[str, None] = '0950e2556799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurantes', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    op.add_column('restaurantes', sa.Column('api_key_prefix', sa.String(length=20), nullable=True))
    op.add_column('restaurantes', sa.Column('api_key_scopes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('restaurantes', sa.Column('api_key_creada_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('restaurantes', sa.Column('n8n_webhook_notificaciones_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurantes', 'n8n_webhook_notificaciones_url')
    op.drop_column('restaurantes', 'api_key_creada_en')
    op.drop_column('restaurantes', 'api_key_scopes')
    op.drop_column('restaurantes', 'api_key_prefix')
    op.drop_column('restaurantes', 'api_key_hash')
    # ### end Alembic commands ###
