"""modelo inicial: restaurantes, usuarios, zonas, mesas, turnos, reservas

Revision ID: a385fda63026
Revises: 
Create Date: 2026-08-04 05:22:12.598175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a385fda63026'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurantes',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Madrid', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantes_slug'), 'restaurantes', ['slug'], unique=True)
    op.create_table('turnos',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('dias_semana', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('duracion_reserva_minutos', sa.Integer(), server_default='90', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_restaurante_id'), 'turnos', ['restaurante_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('restaurante_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('SUPERADMIN', 'ADMIN', 'MANAGER', 'STAFF', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_restaurante_id'), 'usuarios', ['restaurante_id'], unique=False)
    op.create_table('zonas',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurante_id', 'nombre', name='uq_zona_restaurante_nombre')
    )
    op.create_index(op.f('ix_zonas_restaurante_id'), 'zonas', ['restaurante_id'], unique=False)
    op.create_table('mesas',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('zona_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('capacidad_min', sa.Integer(), nullable=False),
    sa.Column('capacidad_max', sa.Integer(), nullable=False),
    sa.Column('forma', sa.Enum('CUADRADA', 'RECTANGULAR', 'CIRCULAR', 'OVALADA', name='forma_mesa'), nullable=False),
    sa.Column('pos_x', sa.Float(), server_default='0', nullable=False),
    sa.Column('pos_y', sa.Float(), server_default='0', nullable=False),
    sa.Column('ancho', sa.Float(), server_default='80', nullable=False),
    sa.Column('alto', sa.Float(), server_default='80', nullable=False),
    sa.Column('rotacion', sa.Float(), server_default='0', nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurante_id', 'nombre', name='uq_mesa_restaurante_nombre')
    )
    op.create_index(op.f('ix_mesas_restaurante_id'), 'mesas', ['restaurante_id'], unique=False)
    op.create_index(op.f('ix_mesas_zona_id'), 'mesas', ['zona_id'], unique=False)
    op.create_table('reservas',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('turno_id', sa.UUID(), nullable=True),
    sa.Column('mesa_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('num_personas', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=150), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=True),
    sa.Column('cliente_email', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'SENTADA', 'FINALIZADA', 'CANCELADA', 'NO_SHOW', name='estado_reserva'), nullable=False),
    sa.Column('origen', sa.Enum('MANUAL', 'IA_N8N', 'GOOGLE_CALENDAR', 'WEB', name='origen_reserva'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_fecha'), 'reservas', ['fecha'], unique=False)
    op.create_index(op.f('ix_reservas_google_event_id'), 'reservas', ['google_event_id'], unique=False)
    op.create_index(op.f('ix_reservas_mesa_id'), 'reservas', ['mesa_id'], unique=False)
    op.create_index(op.f('ix_reservas_restaurante_id'), 'reservas', ['restaurante_id'], unique=False)
    op.create_index(op.f('ix_reservas_turno_id'), 'reservas', ['turno_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_turno_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_restaurante_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_mesa_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_google_event_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_mesas_zona_id'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_restaurante_id'), table_name='mesas')
    op.drop_table('mesas')
    op.drop_index(op.f('ix_zonas_restaurante_id'), table_name='zonas')
    op.drop_table('zonas')
    op.drop_index(op.f('ix_usuarios_restaurante_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_turnos_restaurante_id'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_restaurantes_slug'), table_name='restaurantes')
    op.drop_table('restaurantes')
    # ### end Alembic commands ###
