"""lista de espera

Revision ID: b559e74266a0
Revises: 80e5f6e55868
Create Date: 2026-08-06 06:39:15.789414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b559e74266a0'
down_revision: Union[str, None] = '80e5f6e55868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_espera',
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('turno_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('comensales', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=150), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=True),
    sa.Column('cliente_email', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('ESPERANDO', 'OFRECIDA', 'CONFIRMADA', 'EXPIRADA', 'CANCELADA', name='estado_lista_espera'), nullable=False),
    sa.Column('mesa_ofrecida_id', sa.UUID(), nullable=True),
    sa.Column('oferta_expira_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reserva_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mesa_ofrecida_id'], ['mesas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lista_espera_fecha'), 'lista_espera', ['fecha'], unique=False)
    op.create_index(op.f('ix_lista_espera_restaurante_id'), 'lista_espera', ['restaurante_id'], unique=False)
    op.create_index(op.f('ix_lista_espera_turno_id'), 'lista_espera', ['turno_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lista_espera_turno_id'), table_name='lista_espera')
    op.drop_index(op.f('ix_lista_espera_restaurante_id'), table_name='lista_espera')
    op.drop_index(op.f('ix_lista_espera_fecha'), table_name='lista_espera')
    op.drop_table('lista_espera')
    # ### end Alembic commands ###
